diaryyy/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

diaryyy/blogs/urls.py
# blogs urls.py

from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.BlogList.as_view(), name='all'),
    path('new/', views.BlogCreateView.as_view(), name='new'),
    url(r"by/(?P<username>[-\w]+)/$",views.UserBlog.as_view(),name="for_user"),
    url(r"by/random/(?P<username>[-\w]+)/$",views.RandomBlogList.as_view(),name="random_blog_list"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.BlogDetailView.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.BlogDeleteView.as_view(),name="delete"),
]

diaryyy/diaryyy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('home/', views.Home, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
] +static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

diaryyy/accounts/models.py
# accounts models.py

from django.db import models
from django.contrib import auth

class Signup(models.Model):

    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

diaryyy/blogs/models.py
# blogs models.py

from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

class Blog(models.Model):
    user = models.ForeignKey(User, related_name='blogs', on_delete=models.CASCADE)
    message = models.TextField(unique=False, blank=True)
    created_at = models.DateTimeField(auto_now=True)
    message_html = models.TextField(editable=False)
    blog_image = models.ImageField(default='', upload_to='', blank=False, null=False )

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('home')

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

diaryyy/accounts/forms.py
# accounts forms.py

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
	class Meta:
		fields = ('username', 'email', 'password1', 'password2',)
		model = get_user_model()

		def __init__(self, *args, **kwargs):
			super().__init__(*args, **kwargs)
			self.fields['username'].label.widget.attrs.update({'class': 'form-control'})
			self.fields['email'].widget.attrs.update({'class': 'form-control'})

diaryyy/blogs/forms.py
#blogs forms.py

from django import forms
from . import models

class BlogForm(forms.ModelForm):
    class Meta:
        fields = ('blog_image', 'message')
        model = models.Blog

    def __init__(self, *args, **kwrags):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

diaryyy/accounts/views.py
# accounts views.py

from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView

from . import forms

class SignUp (CreateView):
	form_class = forms.UserCreateForm
	success_url = reverse_lazy('login')
	template_name='accounts/signup.html'

diaryyy/blogs/views.py
# blogs views.py

from django.shortcuts import render, get_object_or_404, redirect
from . import models
from . import forms
from django.contrib.auth.decorators import login_required
from django.views import generic
from braces.views import SelectRelatedMixin
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth import get_user_model
User = get_user_model()

from django.template.defaultfilters import register

@register.filter
def to_blocks_3(value):
    ans = [[], [], []]
    for i in range(len(value)):
        ans[i%3].append(value[i])
    return ans

class BlogList(SelectRelatedMixin, generic.ListView):
    model = models.Blog
    select_related = ('user',)

class RandomBlogList (generic.ListView):
    model = models.Blog
    template_name = 'blogs/user_random_blog.html'

    def get_queryset(self):
        try:
            self.blog_user = User.objects.prefetch_related('blogs').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.blog_user.blogs.order_by('?')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog_user'] = self.blog_user
        return context



class UserBlog(generic.ListView):
    model = models.Blog
    template_name='blogs/user_blog_list.html'

    def get_queryset(self):
        try:
            self.blog_user = User.objects.prefetch_related('blogs').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.blog_user.blogs.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog_user'] = self.blog_user
        return context

class BlogDetailView(SelectRelatedMixin, generic.DetailView):
    model = models.Blog
    select_related= ('user',)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )

class BlogCreateView(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView ):
    fields = ('blog_image', 'message')
    model = models.Blog

    def  form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)

class BlogDeleteView(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    select_related = ('user',)
    model = models.Blog
    success_url = reverse_lazy('blogs:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Blog deleted")
        return super().delete(*args, **kwargs)

diaryyy/diaryyy/views.py
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import redirect


class IndexView(TemplateView):
	template_name = 'index.html'

@login_required
def Home(request):
    return redirect(reverse('blogs:random_blog_list',
					kwargs={'username' :request.user.username }))

diaryyy/accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Bloggg</title>
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
        crossorigin="anonymous">

		<link rel="stylesheet" href="{% static 'CSS/login.css' %}" />
		
        
    </head>

{% block content %}
	<div class="container">

	    <h1>Login Here</h1>
		<form class="signup-form" method="POST">
			{% csrf_token %}
			{% bootstrap_form form %}
			<input type="submit" class="btn btn-primary" value="Log In">
		</form>
	</div>
{% endblock %}

diaryyy/accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Bloggg</title>
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
        crossorigin="anonymous">

		<link rel="stylesheet" href="{% static 'CSS/signup.css' %}" />
		
        
    </head>

{% block content %}
	<div class="container ">

	    <h1>Create Account</h1>
		<form class="signup-form" method="POST">
			{% csrf_token %}
			{% bootstrap_form form %}
			<input type="submit" class="btn btn-primary" value="Sign Up">
		</form>
	</div>
{% endblock %}

diaryyy/blogs/templates/blogs/_blog.html
<div class="blog media">
    <div class="blog-image-div">
        <img class="blog-image" src='{{blog.blog_image.url}}' alt="no image for this blog" width="50%">
    </div>
    <div class="">
        <p>{{blog.message_html|safe}}</p>
    </div>
    <div class="media-body">
            <span class="username">
                <p><a href="{% url 'blogs:for_user' username=blog.user.username %}">@{{blog.user.username}}</a></p>
            </span>
            <time class="time">
                <p><a href="{% url 'blogs:single' username=blog.user.username pk=blog.pk %}">{{blog.created_at}}</a></p>
            </time>
        <div class="media-footer">
            {% if user.is_authenticated and blog.user == user and not hide_delete %}
                <p><a href="{% url 'blogs:delete' pk=blog.pk %}" title="delete" class="btn btn-danger">
                    <span class="text-danger icon-label"></span>Delete
                </a></p>
            {% endif %}
        </div>
    </div>
</div>

diaryyy/blogs/templates/blogs/blog_base.html
{% extends 'base.html' %}
{% block content %}
   <div class="container" style="padding: 0;">
       {% block preblog %} {% endblock %}
       {% block blog_content %} {% endblock %}
       {% block postblog %} {% endblock %}
   </div>
{% endblock %}

diaryyy/blogs/templates/blogs/blog_confirm_delete.html
{% extends 'blogs/blog_base.html' %}
{% block blog_content %}
    <h4>Are you sure you want to delete this blog!</h4>
    <div class="blogs">
        {% include 'blogs/_blog.html' with blog=object hide_delete=True %}
    </div>
    <form class="blog-delete-form" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-simple btn-large btn-danger" value="Delete">
        <a href="{% url 'blogs:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-success">Cancel</a>
    </form>
{% endblock %}

diaryyy/blogs/templates/blogs/blog_detail.html
{% extends 'blogs/blog_base.html' %}
{% block blog_content %}
    <div class="col-md-8">
        {% include 'blogs/_blog.html' %}
    </div>
{% endblock %}

diaryyy/blogs/templates/blogs/blog_form.html
{% extends 'blogs/blog_base.html' %}
{% load bootstrap4 %}
{% block blog_content %}
    <h4>Today's events</h4>
    <form class="blog-form" id="blog-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-simple btn-success" value="Post">
    </form>
{% endblock %}

diaryyy/blogs/templates/blogs/blog_list.html
{% extends 'blogs/blog_base.html' %}
{% block blog_content %}
    <div class="col-md-8">
        {% for blog in blog_list %}
            {% include 'blogs/_blog.html' %}
        {% endfor %}
    </div>
{% endblock %}

diaryyy/blogs/templates/blogs/user_blog_list.html
{% extends 'blogs/blog_base.html' %}

{% block blog_content %}
    <div class="col-md-8">
        {% for blog in blog_list %}
            {% include 'blogs/_blog.html' %}
        {% endfor %}
    </div>
{% endblock %}

diaryyy/blogs/templates/blogs/user_random_blog.html
{% extends 'blogs/blog_base.html' %}

{% block blog_content %}

    <div class="row" style="margin: 50px 0">
        {% with block=blog_list|to_blocks_3 %}
        <div id="col-1" class="col-md-4">
            {% for blog in block.0 %}
                <div class="blog-image-div">
                    <img class="blog-image" src='{{blog.blog_image.url}}' alt="no image for this blog" width="100%">
                    <time class="time">
                        <p><a href="{% url 'blogs:single' username=blog.user.username pk=blog.pk %}">{{blog.created_at}}</a></p>
                    </time>
                </div>
            {% endfor %}
        </div>
        <div id="col-2" class="col-md-4">
            {% for blog in block.1 %}
                <div class="blog-image-div">
                    <img class="blog-image" src='{{blog.blog_image.url}}' alt="no image for this blog" width="100%">
                    <time class="time">
                        <p><a href="{% url 'blogs:single' username=blog.user.username pk=blog.pk %}">{{blog.created_at}}</a></p>
                    </time>
                </div>
            {% endfor %}
        </div>
        <div id="col-3" class="col-md-4">
            {% for blog in block.2 %}
                <div class="blog-image-div">
                    <img class="blog-image" src='{{blog.blog_image.url}}' alt="no image for this blog" width="100%">
                    <time class="time">
                        <p><a href="{% url 'blogs:single' username=blog.user.username pk=blog.pk %}">{{blog.created_at}}</a></p>
                    </time>
                </div>
            {% endfor %}
        </div>

        {% endwith %}
    </div>

{% endblock %}

diaryyy/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Bloggg</title>
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
        crossorigin="anonymous">

    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Diary</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse navbar-ri" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="list-item"><a class="nav-link" href="{% url 'blogs:new' %}">CREATE</a></li>
                        <li class="list-item"><a class="nav-link" href="{% url 'blogs:for_user' username=request.user.username %}">All</a></li>
                        <li class="list-item"><a class="nav-link" href="#">GROUPS</a></li>
                        <li class="list-item"><a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a></li>
                    {% else %}
                        <li class="list-item"><a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a></li>
                        <li class="list-item"><a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    </body>
</html>

diaryyy/templates/index.html
{% extends 'base.html' %}
{% block content %}
	<div class="jumbotron" >
		<p> This is the index page!</p>
	</div>
{% endblock %}